import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Button, Form, Input, Radio } from "antd";
import Prompt from "../components/Prompt";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>story-telephone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>write a story with frens</h1>

        <button className={styles.bigButton}>start a story</button>
        <p className={styles.description}>
          or... if you have a game code, enter it here
        </p>

        <div className={styles.submitStoryCode}>
          <form>
            <input className={styles.storyCodeInput}></input>
          </form>

          <button>submit code</button>
        </div>

        <Prompt />
      </main>
    </div>
  );
}
